const adminPassword = "tohidkhan6332"; // set admin password
let isAdmin = false; // tracks admin login status
function adminLogin(password) {
  if (password === adminPassword) {
    isAdmin = true;
    console.log("Admin login successful!");
  } else {
    console.log("Incorrect admin password.");
  }
}
function executeCommand(command, user) {
  const adminCommands = ["kickInactive", "banUser", "muteUser"];
  if (adminCommands.includes(command) && !isAdmin) {
    console.log("Access denied. Login as admin to use this command.");
    return;
  }
  switch (command) {
    case "kickInactive":
      console.log(${user} kicked all inactive users from the server.);
      // Add actual kick logic here
      break;
    case "banUser":
      console.log(${user} banned a user from the server.);
      // Add actual ban logic here
      break;
    case "muteUser":
      console.log(${user} muted a user in the server.);
      // Add actual mute logic here
      break;
    default:
      console.log("Invalid command.");
      break;
  }
}






// Example usage:
adminLogin("wrongPass"); // test incorrect password
executeCommand("kickInactive", "RegularUser"); // should deny access
adminLogin("tohidkhan6332"); // test correct password
executeCommand("kickInactive", "AdminUser"); // should grant access
